%lex

%%

\s+ /* skip whitespaces */
\d+ return 'NUMBER'

[+\-] return 'ADDITIVE_OPERATOR'
[*/] return 'MULTIPLICATIVE_OPERATOR'

/lex



// ----------------
// syntactic grammar

%%

Expression
 : AdditiveExpression
 ;

AdditiveExpression
 : AdditiveExpression ADDITIVE_OPERATOR MultiplicativeExpression 
        {
            $$ = {
                type: 'BinaryExpression',
                op: $2,
                left: $1,
                right: $3
            }
        }
 | MultiplicativeExpression
 ;


MultiplicativeExpression
 :  MultiplicativeExpression MULTIPLICATIVE_OPERATOR PrimaryExpression
        {
            $$ = {
                type: 'BinaryExpression',
                op: $2,
                left: $1,
                right: $3
            }
        }
 |  PrimaryExpression
 ;

PrimaryExpression
 : Literal
 | ParenthesizedExpression
 ;

Literal
 : NumericLiteral
 ;

NumericLiteral
 : NUMBER 
        {
           $$ = {
            type: 'NumericLiteral',
            value: Number($1)
           }
        }
 ;

ParenthesizedExpression
 : '(' Expression ')' { $$ = $2 }
 ;