// tokenizer

%lex

%%

\s+         return null 
\d+         return 'NUMBER'
/lex

%%
Array
  : '[' ValueList ']' {$$ = $2}
  | '[' ']' {$$ =  []}
  ;

ValueList
  : ValueWithComma  {$$  = [$1]}
  | ValueWithComma ValueList {$2.push($1), $$ = $2} 
  ;

ValueWithComma
  : Value ',' {$$ = $1}
  | Value
  ;

Value
  : NUMBER  {$$ = Number($1)}
  ;

