// tokenizer

%lex

%%

\s+         return null 
\d+         return 'NUMBER'
/lex

%%
Array
  : '[' OptValueList ']' {$$ = $2}
  ;

OptValueList
  : ValueList
  | /*empty*/ {$$ = []}
  ;

ValueList
  : Value  {$$  = [$1]}
  | ValueList ',' Value  {$1.push($3), $$ = $1} 
  ;

Value
  : NUMBER  {$$ = Number($1)}
  ;

